# -*- coding: utf-8 -*-
"""NCAAW_Draft_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DzRd8GbB2M3dl9NMQbgvqZ1oLIVxxwHw

# **NCAAW Draft Model**
"""

'''
get team data from sports reference

output: csv with all ncaaw teams includes, season_year, conference, team, wins, losses, team URL
'''
import re
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup, Comment
from urllib.parse import urljoin

BASE = "https://www.sports-reference.com"
YEAR = 2025

# Conference name -> slug used in Sports-Reference URL
CONFERENCES = [
    ("Southeastern Conference", "sec"),
    ("Big Ten Conference", "big-ten"),
    ("Missouri Valley Conference", "mvc"),
    ("Atlantic Coast Conference", "acc"),
    ("West Coast Conference", "wcc"),
    ("Atlantic 10 Conference", "atlantic-10"),
    ("Big 12 Conference", "big-12"),
    ("Big East Conference", "big-east"),
    ("Horizon League", "horizon"),
    ("America East Conference", "america-east"),
    ("Western Athletic Conference", "wac"),
    ("Mountain West Conference", "mwc"),
    ("Coastal Athletic Association", "coastal"),
    ("American Athletic Conference", "aac"),
    ("Ivy League", "ivy"),
    ("Southern Conference", "southern"),
    ("Big Sky Conference", "big-sky"),
    ("Mid-Eastern Athletic Conference", "meac"),
    ("Sun Belt Conference", "sun-belt"),
    ("Summit League", "summit"),
    ("Southwest Athletic Conference", "swac"),
    ("Ohio Valley Conference", "ovc"),
    ("Conference USA", "cusa"),
    ("Big West Conference", "big-west"),
    ("Atlantic Sun Conference", "atlantic-sun"),
    ("Mid-American Conference", "mac"),
    ("Big South Conference", "big-south"),
    ("Metro Atlantic Athletic Conference", "maac"),
    ("Southland Conference", "southland"),
    ("Northeast Conference", "northeast"),
    ("Patriot League", "patriot"),
]

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Referer": "https://www.sports-reference.com/",
}

# Women’s team pages on Sports-Reference typically use these patterns
TEAM_HREF_PATTERNS = [
    re.compile(r"^/cbb/schools/[^/]+/women/\d{4}\.html$"),
    re.compile(r"^/cbb/schools/[^/]+/women/?$"),
    re.compile(r"^/cbb/schools/[^/]+/women\.html$"),
]

def get_soup(url: str) -> BeautifulSoup:
    r = requests.get(url, headers=HEADERS, timeout=30)
    r.raise_for_status()
    return BeautifulSoup(r.text, "html.parser")

def soups_including_comments(soup: BeautifulSoup):
    """Sports-Reference sometimes hides tables inside HTML comments."""
    soups = [soup]
    for c in soup.find_all(string=lambda t: isinstance(t, Comment)):
        if "<table" in c:
            soups.append(BeautifulSoup(c, "html.parser"))
    return soups

def find_standings_table(soup: BeautifulSoup):
    """Find standings table (id='standings' or heuristic match)."""
    for s in soups_including_comments(soup):
        t = s.find("table", id="standings")
        if t is not None:
            return t

    # heuristic fallback: table with W, L, W-L%
    for s in soups_including_comments(soup):
        for table in s.find_all("table"):
            thead = table.find("thead")
            if not thead:
                continue
            headers = [th.get_text(strip=True) for th in thead.find_all("th")]
            hs = set(headers)
            if {"W", "L", "W-L%"}.issubset(hs) and ("School" in hs or "Team" in hs):
                return table
    return None

def get_cell_text(tr, data_stat: str) -> str | None:
    """Extract cell text using Sports-Reference's data-stat attribute."""
    td = tr.find(["td", "th"], attrs={"data-stat": data_stat})
    if td is None:
        return None
    return td.get_text(strip=True)

def extract_teams_wins_losses(table, conference_name: str, conference_slug: str, year: int):
    teams = []
    seen = set()

    tbody = table.find("tbody")
    if not tbody:
        return teams

    for tr in tbody.find_all("tr"):
        # Skip separator/header rows inside tbody
        if tr.get("class") and ("thead" in tr.get("class") or "spacer" in tr.get("class")):
            continue

        a = tr.find("a", href=True)
        if not a:
            continue

        href = a["href"].strip()
        if not any(p.match(href) for p in TEAM_HREF_PATTERNS):
            continue

        team_name = a.get_text(strip=True)
        team_url = urljoin(BASE, href)
        # /cbb/schools/<team_id>/...
        team_id = href.split("/")[3]

        # Wins / losses: usually data-stat="wins" and data-stat="losses"
        wins = get_cell_text(tr, "wins")
        losses = get_cell_text(tr, "losses")

        # Sometimes the columns can be named differently; fallback to visible W/L columns:
        if wins is None or losses is None:
            # try common alternates
            wins = wins or get_cell_text(tr, "w")
            losses = losses or get_cell_text(tr, "l")

        # W-L% if you want it
        wl_pct = get_cell_text(tr, "win_loss_pct") or get_cell_text(tr, "win_loss_perc")

        if wins is None or losses is None:
            # As a last resort, attempt to locate the W/L by header text positions
            # (rarely needed, but keeps the scraper resilient)
            tds = [c.get_text(strip=True) for c in tr.find_all(["td", "th"])]
            # Heuristic: find first integer-like pair
            nums = [x for x in tds if re.fullmatch(r"-?\d+", x)]
            # not guaranteed; if missing, leave blank
            if wins is None and len(nums) >= 2:
                wins = nums[0]
            if losses is None and len(nums) >= 2:
                losses = nums[1]

        key = (conference_slug, year, team_id)
        if key in seen:
            continue
        seen.add(key)

        teams.append({
            "season_year": year,
            "conference": conference_name,
            "conference_slug": conference_slug,
            "team": team_name,
            "team_id": team_id,
            "wins": int(wins) if wins and wins.isdigit() else wins,
            "losses": int(losses) if losses and losses.isdigit() else losses,
            "wl_pct": float(wl_pct) if wl_pct and re.fullmatch(r"\d*\.\d+", wl_pct) else wl_pct,
            "team_url": team_url,
        })

    return teams

def scrape_conference(conference_name: str, conference_slug: str, year: int):
    url = f"{BASE}/cbb/conferences/{conference_slug}/women/{year}.html"
    soup = get_soup(url)
    table = find_standings_table(soup)
    if table is None:
        raise RuntimeError(f"Could not find standings table at {url}")

    rows = extract_teams_wins_losses(table, conference_name, conference_slug, year)
    if not rows:
        raise RuntimeError(f"Found standings table but extracted 0 teams at {url}")
    return rows

def scrape_all_conferences(conferences, year: int, sleep_s: float = 1.0) -> pd.DataFrame:
    all_rows = []
    for conf_name, conf_slug in conferences:
        try:
            rows = scrape_conference(conf_name, conf_slug, year)
            all_rows.extend(rows)
            print(f"[OK] {conf_name}: {len(rows)} teams")
        except Exception as e:
            print(f"[FAIL] {conf_name} ({conf_slug}): {e}")
        time.sleep(sleep_s)

    df = pd.DataFrame(all_rows)

    # De-dupe (shouldn’t be necessary, but safe)
    df = df.drop_duplicates(subset=["season_year", "team_id"]).sort_values(["conference", "team"]).reset_index(drop=True)
    return df

if __name__ == "__main__":
    df = scrape_all_conferences(CONFERENCES, YEAR, sleep_s=1.0)

    out = f"ncaaw_teams_wins_losses_{YEAR}.csv"
    df[["season_year", "conference", "team", "wins", "losses", "team_url"]].to_csv(out, index=False)

    print(f"\nExported {len(df)} teams to {out}")

"""
Loop through NCAAW team URL and scrapes per game and adv table for player stats

Output: One CSV with one row per player-season, including per-game + advanced + team context.
"""

import re
import time
import random
import requests
import pandas as pd
from bs4 import BeautifulSoup, Comment
from urllib.parse import urlparse

# -----------------------------
# CONFIG
# -----------------------------
TEAM_CSV_PATH = "/content/NCAAWTeamData.csv"

OUT_CSV_PATH = "/content/ncaaw_all_players_2025.csv"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Referer": "https://www.sports-reference.com/",
}

REQUEST_TIMEOUT = 30
MAX_RETRIES = 3
SLEEP_BETWEEN_TEAMS = (1.0, 2.0)

# Sports-Reference women team season pages typically use these IDs
PER_GAME_TABLE_IDS = ["players_per_game", "per_game"]
ADV_TABLE_IDS = ["players_advanced", "advanced"]

TEAM_TOTALS_RE = re.compile(r"team totals|totals", re.IGNORECASE)

# If you get blocked, increase this to (2.0, 4.0)
# SLEEP_BETWEEN_TEAMS = (2.0, 4.0)


# -----------------------------
# HTTP + HTML parsing
# -----------------------------
def fetch_html(url: str, session: requests.Session) -> str:
    last_err = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            r = session.get(url, headers=HEADERS, timeout=REQUEST_TIMEOUT)
            r.raise_for_status()
            return r.text
        except Exception as e:
            last_err = e
            time.sleep(1.25 * attempt)
    raise RuntimeError(f"Failed to fetch {url}. Last error: {last_err}")


def soups_including_comments(html: str):
    soup = BeautifulSoup(html, "html.parser")
    soups = [soup]
    for c in soup.find_all(string=lambda t: isinstance(t, Comment)):
        if "<table" in c:
            soups.append(BeautifulSoup(c, "html.parser"))
    return soups


def find_table_by_ids(soups, table_ids):
    for tid in table_ids:
        for s in soups:
            t = s.find("table", id=tid)
            if t is not None:
                return t, tid
    return None, None


def parse_player_cell(tr):
    """
    Robustly extract player name + href from first <th>.
    Works even if there is no data-stat="player".
    """
    th = tr.find("th")
    if th is None:
        return None, None, None

    player_name = th.get_text(strip=True) or None
    a = th.find("a", href=True)
    player_href = a["href"].strip() if a else None
    player_id = player_href.split("/")[-1].replace(".html", "") if player_href else None
    return player_name, player_href, player_id


def table_to_df_robust(table) -> pd.DataFrame:
    """
    Parse a SR table to DF:
      - player name from <th>
      - all td with data-stat
    """
    tbody = table.find("tbody")
    if not tbody:
        return pd.DataFrame()

    rows = []
    for tr in tbody.find_all("tr"):
        # Skip embedded header rows
        if tr.get("class") and "thead" in tr.get("class"):
            continue

        player, player_href, player_id = parse_player_cell(tr)
        if not player:
            continue
        if TEAM_TOTALS_RE.search(player):
            continue

        row = {
            "player": player,
            "player_href": player_href,
            "player_id": player_id,
        }

        for td in tr.find_all("td"):
            ds = td.get("data-stat")
            if ds:
                row[ds] = td.get_text(strip=True)

        rows.append(row)

    df = pd.DataFrame(rows)
    return df


def scrape_team_players(team_url: str, session: requests.Session) -> pd.DataFrame:
    html = fetch_html(team_url, session)
    soups = soups_including_comments(html)

    per_table, per_id = find_table_by_ids(soups, PER_GAME_TABLE_IDS)
    adv_table, adv_id = find_table_by_ids(soups, ADV_TABLE_IDS)

    if per_table is None and adv_table is None:
        raise RuntimeError(f"No player tables found (checked {PER_GAME_TABLE_IDS} and {ADV_TABLE_IDS}).")

    per_df = table_to_df_robust(per_table) if per_table is not None else pd.DataFrame()
    adv_df = table_to_df_robust(adv_table) if adv_table is not None else pd.DataFrame()

    # If one table is missing, return the other (still useful)
    if per_df.empty and not adv_df.empty:
        adv_df["source_missing"] = "per_game"
        adv_df["per_game_table_id_used"] = per_id
        adv_df["advanced_table_id_used"] = adv_id
        return adv_df

    if adv_df.empty and not per_df.empty:
        per_df["source_missing"] = "advanced"
        per_df["per_game_table_id_used"] = per_id
        per_df["advanced_table_id_used"] = adv_id
        return per_df

    if per_df.empty and adv_df.empty:
        return pd.DataFrame()

    # Choose join key
    join_key = "player_id" if per_df["player_id"].notna().any() else "player"

    # Prefix non-identity columns to avoid collisions
    id_cols = {"player", "player_id", "player_href"}
    per_cols = [c for c in per_df.columns if c not in id_cols]
    adv_cols = [c for c in adv_df.columns if c not in id_cols]

    per_df = per_df.rename(columns={c: f"pg_{c}" for c in per_cols})
    adv_df = adv_df.rename(columns={c: f"adv_{c}" for c in adv_cols})

    merged = pd.merge(per_df, adv_df, on=join_key, how="outer")
    merged["per_game_table_id_used"] = per_id
    merged["advanced_table_id_used"] = adv_id
    return merged


# -----------------------------
# Orchestrator: all teams
# -----------------------------
def extract_team_id_from_url(team_url: str) -> str | None:
    """
    From: https://www.sports-reference.com/cbb/schools/albany-ny/women/2025.html
    -> albany-ny
    """
    try:
        path = urlparse(team_url).path.strip("/").split("/")
        # ["cbb","schools","albany-ny","women","2025.html"]
        if len(path) >= 3 and path[0] == "cbb" and path[1] == "schools":
            return path[2]
    except Exception:
        pass
    return None


def build_all_players(team_csv_path: str) -> pd.DataFrame:
    teams = pd.read_csv(team_csv_path)

    # Be flexible: if your sheet uses a different URL column name, map it here
    if "team_url" not in teams.columns:
        # common alternatives
        for alt in ["url", "URL", "Team URL", "team_page", "team_page_url"]:
            if alt in teams.columns:
                teams = teams.rename(columns={alt: "team_url"})
                break

    if "team_url" not in teams.columns:
        raise ValueError("Team CSV must contain a 'team_url' column (or rename your URL column to team_url).")

    team_context_cols = [c for c in teams.columns if c != "team_url"]

    all_players = []
    with requests.Session() as session:
        for i, row in teams.iterrows():
            team_url = row["team_url"]
            team_name = row.get("team", f"row_{i}")
            team_id = extract_team_id_from_url(team_url)

            try:
                df_team_players = scrape_team_players(team_url, session)

                if df_team_players.empty:
                    print(f"[WARN] {team_name}: 0 player rows parsed")
                    continue

                # Add team context columns onto every player row
                for c in team_context_cols:
                    df_team_players[c] = row[c]
                df_team_players["team_url"] = team_url
                df_team_players["team_id"] = team_id

                all_players.append(df_team_players)
                print(f"[OK] {team_name}: {len(df_team_players)} player rows")

            except Exception as e:
                print(f"[FAIL] {team_name}: {e}")

            time.sleep(random.uniform(*SLEEP_BETWEEN_TEAMS))

    if not all_players:
        return pd.DataFrame()

    df_all = pd.concat(all_players, ignore_index=True)

    # Coerce numeric columns where sensible
    exclude = {
        "player", "player_id", "player_href",
        "team", "conference", "conference_slug", "team_url", "team_id", "record"
    }
    for c in df_all.columns:
        if c not in exclude:
            df_all[c] = pd.to_numeric(df_all[c], errors="ignore")

    return df_all


if __name__ == "__main__":
    df_players = build_all_players(TEAM_CSV_PATH)
    df_players.to_csv(OUT_CSV_PATH, index=False)
    print(f"\nExported {len(df_players)} player rows to: {OUT_CSV_PATH}")
    print(df_players.head(10))

'''
Clustering Model using sklearn
'''

import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.pipeline import Pipeline
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import files

# Load Data
PATH = "ncaaw_all_players_2025.csv"
df = pd.read_csv(PATH)
print("Rows, Cols:", df.shape)


features = [
    # Usage & Scoring Role
    "pts_per_g",
    "fga_per_g",
    "usg_pct",

    # Shooting Profile
    "ts_pct",
    "fg3_pct",
    "fg3a_per_g",
    "fta_per_g",

    # Playmaking
    "ast_per_g",
    "ast_pct",
    "tov_per_g",

    # Rebounding / Size Proxy
    "treb_per_g",
    "treb_pct",

    # Defense
    "dws",
    "stl_per_g",
    "blk_per_g",
]

missing = [c for c in features if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns in CSV: {missing}\n"
                     f"Available columns example: {list(df.columns)[:30]}")

X = df[features].copy()

# Convert to numeric (coerce errors to NaN)
for c in features:
    X[c] = pd.to_numeric(X[c], errors="coerce")

# Optional: convert percent columns from 0–100 to 0–1 if needed
pct_cols = ["usg_pct", "ts_pct", "fg3_pct", "ast_pct", "trb_pct"]
for c in pct_cols:
    if c in X.columns:
        med = np.nanmedian(X[c].values)
        # heuristic: if median > 1.5, likely percent out of 100
        if med > 1.5:
            X[c] = X[c] / 100.0

# -------------------------
# 3) Choose k (silhouette sweep)
# -------------------------
k_values = list(range(4, 11))
sil_scores = []

for k in k_values:
    pipe = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("kmeans", KMeans(n_clusters=k, random_state=42, n_init="auto")),
    ])
    labels = pipe.fit_predict(X)

    X_imp = pipe.named_steps["imputer"].transform(X)
    X_scaled = pipe.named_steps["scaler"].transform(X_imp)
    sil = silhouette_score(X_scaled, labels)
    sil_scores.append(sil)

plt.figure()
plt.plot(k_values, sil_scores, marker="o")
plt.xlabel("k (number of clusters)")
plt.ylabel("Silhouette score")
plt.title("Silhouette score by k")
plt.show()

best_k = k_values[int(np.argmax(sil_scores))]
print("Best k by silhouette:", best_k)

# Set K
K = best_k

# -------------------------
# 4) Fit final KMeans
# -------------------------
final_pipe = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("kmeans", KMeans(n_clusters=K, random_state=42, n_init="auto")),
])

df["cluster"] = final_pipe.fit_predict(X)

# -------------------------
# 5) Visualization: PCA to 2D
# -------------------------
# PCA is for visualization only (clusters were fit in full feature space)
X_imp = final_pipe.named_steps["imputer"].transform(X)
X_scaled = final_pipe.named_steps["scaler"].transform(X_imp)

pca = PCA(n_components=2, random_state=42)
X_2d = pca.fit_transform(X_scaled)

df["pca1"] = X_2d[:, 0]
df["pca2"] = X_2d[:, 1]

print("PCA explained variance (2 components):", pca.explained_variance_ratio_.round(3),
      "Total:", pca.explained_variance_ratio_.sum().round(3))

plt.figure(figsize=(9, 6))
plt.scatter(df["pca1"], df["pca2"], c=df["cluster"], s=10)
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.title("NCAAW Player Archetypes (KMeans clusters) — PCA visualization")
plt.show()

# -------------------------
# 6) Cluster profiles (means in original units, after imputation)
# -------------------------
X_imputed_df = pd.DataFrame(X_imp, columns=features, index=df.index)

cluster_profile = (
    pd.concat([df[["cluster"]], X_imputed_df], axis=1)
      .groupby("cluster")[features]
      .mean()
      .round(3)
)

print("\nCluster counts:")
print(df["cluster"].value_counts().sort_index())

print("\nCluster profiles (feature means):")
display(cluster_profile)

# -------------------------
# 7) Export
# -------------------------
OUT_PATH = "ncaaw_players_with_clusters_2025.csv"
df.to_csv(OUT_PATH, index=False)
print("Wrote:", OUT_PATH)

# download
files.download(OUT_PATH)